url: https://www.404podcast.org
baseurl:
title: 404podcast
subtitle:  Những câu chuyện từ hai hackers ở xứ Silicon Valley.
author: Công nghệ 404
simple_search: http://google.com/search
description: Những câu chuyện từ hai hackers ở xứ Silicon Valley.
name: tufte
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
permalink: /episodes/:short_year/:title
timezone: Asia/Saigon
excerpt_separator: <!--more-->
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'UploadToGithub.Rakefile', 'README.md']
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
podcast_url: http://www.404podcast.org
podcast_album_art: /assets/img/404.png
podcast_title: Công nghệ 4.04 | Technology 4.04
podcast_owner: Thai Duong and Huan Truong
podcast_email: hello@404podcast.org
podcast_category_one: Technology
podcast_category_two: Science
podcast_category_three: Society &amp; Culture
podcast_explicit: "no"
podcast_author: Thai Duong and Huan Truong
podcast_description: Stories from two Vietnamese hackers at Silicon Valley. Những câu chuyện từ hai hackers ở xứ Silicon Valley.
podcast_summary: Chúng tôi mang Silicon Valley và nước Mỹ đến với Việt Nam qua những câu chuyện về khoa học, kỹ thuật, cuộc sống.
podcast_subtitle: Những câu chuyện từ hai hackers ở xứ Silicon Valley, Hoa Kỳ.
git:
  branch: master
transfer:
  command: rsync
  settings: -av
  source: _site/
